name: "CI Build"
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Install sbt
      uses: coursier/setup-action@v1
      with:
        apps: sbt
        
    - name: Build
      run: sbt clean compile